config/routes.rb
Rails.application.routes.draw do

  get '/wards' => 'api#wards'
  get '/municipalities' => 'api#municipalities'
  get '/districts' => 'api#districts'

  # get 'welcome/index'
  #
  # get "exports/index"
  # get 'exports/regions'
  # get 'exports/municipalities'
  # get 'exports/wards'
  get '/exports/:region_id/index', to: 'exports#index', as: :export_region
  # get '/exports/:region_id/senat', to: 'exports#senat'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :commisaries, :controllers => {:registrations => "commisaries/registrations"}
  resources :commisaries, only: [:index, :show, :new, :destroy, :edit, :update]
  resources :events, only: [:index]
  resources :regions, only: [:index, :show]
  resources :users, only: [:index]

  # mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get '/users/:id' => "commisaries#index", as: "user"
  root 'welcome#index'

  get '/stats', to: 'stats#index'

  # get '/auth/:provider/callback', to: 'sessions#create'
end

app/models/commisary.rb
# encoding: utf-8
class Commisary < ApplicationRecord

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable

  before_validation :fix_params

  belongs_to :user, required: false
  belongs_to :town_hall, required: false
  has_many :events, as: :eventable

  validates :name, length: { minimum: 5 }
  validates :birth_number, length: { minimum: 8 }
  validates :address, length: { minimum: 12 }
  validates :postal_address, length: { minimum: 12 }, allow_blank: true
  # validates :email, presence: true, length: { minimum: 5 }
  validates :ward, presence: true, uniqueness: true

  #validates :party_member, acceptance: true, acceptance: { message: 'nesmíte být členem jiné strany' }
  #validates :party_voter, acceptance: true, acceptance: { message: 'musíte volit Svobodné' }

  belongs_to :ward

  after_create :send_signup_confirmation_email
  after_update :send_update_confirmation_email
  before_destroy :send_destroy_confirmation_email

  attr_accessor :region_id, :municipality_id, :district_id

  def fix_params
    fix_birth_number
    fix_phone
  end

  def fix_birth_number
    parts = birth_number.match(/\A(\d{6})\/?(\d{3,4})\z/)
    if parts
      self.birth_number=[parts[1],parts[2]].join('/')
    end
  end

  def fix_phone
    self.phone = phone.gsub(/ /,'').match(/\A(\+420)?(.*)\z/)[2]
  end

  def send_signup_confirmation_email
    CommisaryMailer.signup_confirmation(self).deliver
  end

  def send_update_confirmation_email
    unless (%w(last_sign_in_at current_sign_in_at last_sign_in_ip current_sign_in_ip sign_in_count updated_at)-changed_attributes.keys).empty?
      CommisaryMailer.update_confirmation(self).deliver
    end
  end

  def send_destroy_confirmation_email
    CommisaryMailer.destroy_confirmation(self).deliver
  end

  def shipping_address
  	postal_address.blank? ? address : postal_address
  end

  def password_required?
    false
  end

  def self.send_final_emails
    errors=[]
    all.order(:id).each{|commisary|
      begin
        CommisaryMailer.final(commisary).deliver
        puts "#{commisary.id} delivered"
      rescue Net::SMTPAuthenticationError, Net::SMTPServerBusy, Net::SMTPSyntaxError, Net::SMTPFatalError, Net::SMTPUnknownError => e
        puts "Mail for #{commisary.email} (#{commisary.id}) could not be sent"
        errors << commisary.id
      end
    }
    errors
  end

  attr_accessor :municipality_id, :region_id, :district_id
  attr_accessor :party_member, :party_voter

  def town_hall
    ward.try(:town_hall)
  end

  def district
    ward.try(:district)
  end

  def municipality
    town_hall.try(:municipality)
  end

  def region
    municipality.try(:region)
  end

end

app/controllers/commisaries/registrations_controller.rb
class Commisaries::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  skip_before_action :require_no_authentication, :only => [ :new, :create ]

  def new
    permitted = params.require(:commisary).permit(:ward_id)
    @commisary=Commisary.new(permitted)
    ward=Ward.find_by_id(@commisary.ward_id)
    if ward.nil?
      flash[:error] = "Neznámý okrsek, vyberte prosím znovu"
      redirect_to new_commisary_path
    elsif ward.taken?
      flash.now[:error] = "Tento okrsek je již obsazený"
    end
    #super
  end

  # POST /resource
  def create
    params[:commisary][:user_id]=current_user.try(:id)
    password=Devise.friendly_token.first(8)
    params[:commisary][:password]=password
    params[:commisary][:password_confirmation]=password
    build_resource(sign_up_params)

    authorize! :create, resource
    resource.save
    yield resource if block_given?
    if resource.persisted?
      resource.events.create(default_event_params.merge({
        command: "CreateCommisary",
        name: "CommisaryCreated",
        changes: resource.previous_changes
      }))
      set_flash_message! :notice, :signed_up
      sign_up(resource_name, resource) unless current_user
      respond_with resource, location: after_sign_up_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  def update
    super
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :birth_number, :address, :postal_address, :phone, :email, :region_id, :municipality_id, :district_id, :ward_id, :user_id, :party_member, :party_voter])
  end

end

app/controllers/commisaries_controller.rb
class CommisariesController < ApplicationController
  before_action :authenticate_user!, only: :index
  before_action :authenticate_person!, except: :new
  before_action :set_commisary, only: [:show, :edit, :update]

  def new
    authorize! :create, Commisary
  end

  def edit
    authorize! :update, @commisary
  end

  def update
    respond_to do |format|
      if @commisary.update(commisary_params)
        @commisary.events.create(default_event_params.merge({
          command: "UpdateCommisary",
          name: "CommisaryUpdated",
          changes: @commisary.previous_changes
        }))
        format.html { redirect_to @commisary, notice: 'Registrace byla úspěšně opravena.' }
        format.json { render :show, status: :ok, location: @commisary }
      else
        format.html { render :edit }
        format.json { render json: @commisary.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @commisaries = Commisary.accessible_by(current_ability)
  end

  def show
  end

  def destroy
    if current_commisary
      current_commisary.destroy
      flash[:notice]='Vaše registrace byla zrušena.'
      Event.create(default_event_params.merge({
        command: "DeleteCommisary",
        name: "CommisaryDeleted",
        eventable_id: params[:id],
        eventable_type: "Commisary"
      }))
      redirect_to "/"
    else
      current_user.commisaries.find(params[:id]).destroy
      Event.create(default_event_params.merge({
        command: "DeleteCommisary",
        name: "CommisaryDeleted",
        eventable_id: params[:id],
        eventable_type: "Commisary"
      }))
      respond_to do |format|
        format.html { redirect_to commisaries_path, notice: 'Registrace byla zrušena.' }
        format.json { head :no_content }
      end
    end
  end

  private
    def set_commisary
      if commisary_signed_in?
        @commisary = current_commisary
      else
        @commisary = current_user.commisaries.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commisary_params
      params.fetch(:commisary, {}).permit(:name, :birth_number, :address, :phone, :postal_address)
    end
end

app/views/commisaries/_ward.html.erb
<tr><th>Kraj: </th><td><%=@commisary.region.name%></td></tr>
<tr><th>Obec: </th><td><span class="pull-right"><%= image_tag(@commisary.ward.town_hall.heraldry_path, width: '50px') %></span><%=@commisary.municipality.name%></td></tr>
<% if @commisary.ward.district %>
<tr><th>Městská část / obvod:</th><td><%= @commisary.ward.district.name %></td></tr>
<% end %>
<% if @commisary.ward.town_hall.address %>
<tr><th>Adresa úřadu:</th><td><%=@commisary.ward.town_hall.address.gsub("\n",', ')%></td></tr>
<% end %>
<tr><th>Okrsek: </th><td><%=@commisary.ward.external_id%></td></tr>

app/views/commisaries/edit.html.erb
<%
  page_title "Registrace do volební komise"
  breadcrumb :commisary_edit, @commisary
%>

<div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Oprava registrace do okrskové volební komise</h3>
          </div>
    <div class="panel-body">
  <% if 1==0 #!@commisary.ward.town_hall.region.registration_ends_at.blank? && @commisary.ward.town_hall.region.registration_ends_at < Time.now %>
    <strong>Registrace do okrskových volebních komisí jsou již uzavřeny.</strong>
  <% else %>
    <!-- <table class="table"><%=render partial: 'commisaries/ward'%></table> -->
    <!-- <h2>Údaje osoby</h2> -->
    <%= simple_form_for(@commisary) do |f| %>
      <%= f.input :name %>
      <%= f.input :birth_number, hint: '(vzor: 20.1.1980)' %>
      <%= f.input :address, placeholder: 'Ulice 536, 111 00 Praha 1', hint: '<strong>Dle občanky!</strong> (vzor: Perucká 2196, 120 00 Praha 2)'.html_safe %>
      <%= f.input :phone, hint: '(vzor: 773697983)' %>
      <%= f.input :email, placeholder: 'mach@svobodni.cz', hint: '(vzor: mach@svobodni.cz)', disabled: true %>
      <%= f.input :postal_address, placeholder: 'Ulice 536, 111 00 Praha 1', hint: '<strong>Vyplňujte jen pokud se liší od trvalého bydliště</strong>'.html_safe %>
      <%= f.submit "Uložit opravu", class: "btn btn-primary btn-block btn-lg" %>
    <% end %>
  <% end %>
</div>
</div>

app/views/commisaries/index.html.erb
<%
  page_title "Vaše registrace do komisí"
  breadcrumb :commisaries
%>

<% if configatron.registration_allowed %>
  <p class="perex">Do okrskových volebních komisí máte zaregistrovány tyto osoby. Uzávěrka registrací je <%=l configatron.registration_ends_at %>, ihned poté odesíláme delegační dopisy jednotlivým starostům.</p>
<% else %>
  <p class="perex">Registrace jsou uzavřeny, údaje jsme odeslali starostům. Registrace nelze měnit. Pokud potřebujete registraci zrušit, můžete písemně na radnici.</p>
<% end %>

<% if @commisaries.empty? %>
  <p class="alert alert-warning">Zatím jste nikoho nezaregistroval</p>
<% end %>

<%= link_to("+ Zaregistrovat novou osobu", new_commisary_path, class: "btn btn-primary pull-right") if can? :create, Commisary %>

<% unless @commisaries.empty? %>
<div class="panel panel-primary">
  <div class="panel-body">
<table class="table table-striped table-condensed">
  <thead>
    <tr><th>Jméno</th><th>Kraj</th><th>Obec</th><th>Číslo okrsku</th><th style="text-align: right;">Akce</th></tr>
  </thead>
  <tbody>
    <% @commisaries.each do |commisary| %>
    <tr><td><%=commisary.name%></td><td><%=commisary.ward.town_hall.region.name%><td><%=commisary.ward.town_hall.name%></td><td><%=commisary.ward.external_id%></td><td style="text-align: right;"><%= link_to "Detail", commisary, class: "btn btn-xs btn-default" %></td></tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<% end %>

app/views/commisaries/new.html.erb
<%
  @commisary = Commisary.new
  page_title "Registrace do okrskové volební komise"
  breadcrumb :ward, @commisary.ward
%>

<%# @town_hall = TownHall.first %>
<%# @commisary = Commisary.new(ward: Ward.first) %>

<div class="panel panel-primary">
  <div class="panel-heading">Výběr okrsku</div>
  <div class="panel-body">

<div class="col-md-12" role="main">
  <% if 1==0 #!@commisary.ward.town_hall.region.registration_ends_at.blank? && @commisary.ward.town_hall.region.registration_ends_at < Time.now %>
    <strong>Registrace do okrskových volebních komisí jsou již uzavřeny.</strong>
  <% else %>
    <%= simple_form_for(@commisary, url: new_commisary_registration_path, method: :get, html: { class: 'form-horizontal' }) do |f| %>
      <%= f.input :region_id, as: :select, collection: Region.accessible_by(current_ability).includes(:municipalities).where("municipalities.registration_allowed"=>true).order(:name), include_blank: false, prompt: true, input_html: {id: :region_id, class: 'step1'} %>
      <%= f.input :municipality_id, as: :select, collection: [], include_blank: false, prompt: true, input_html: {id: :municipality_id, class: 'step2'} %>
      <%= f.input :district_id, as: :select, collection: [], include_blank: false, prompt: false, input_html: {id: :district_id, class: 'step3'} %>
      <%= f.input :ward_id, as: :select, collection: [], include_blank: false, prompt: true, input_html: {id: :ward_id, class: 'step4'} %>
      <%= f.submit "Vyplnit přihlášku >", class: "btn btn-primary pull-right" %>
    <% end %>
    <p>Informativní <a href="https://volby.tmapy.cz/" target="_blank">mapa volebních okrsků</a></p>
  <% end %>
</div>

</div>
</div>
<script></script>

app/views/commisaries/show.html.erb
<% page_title "Detail registrace" %>
<% breadcrumb :commisary, @commisary %>

<% if configatron.registration_allowed %>
  <p class="perex">Až do uzávěrky <%=l configatron.registration_ends_at%> můžete opravovat a doplňovat své údaje. Poté je předáme na příslušnou radnici.</p>
<% else %>
  <p class="perex">Registrace jsou uzavřeny, údaje jsme odeslali starostům. Pokud potřebujete registraci zrušit, můžete písemně na radnici.</p>
<% end %>

<div class="panel panel-primary">
  <div class="panel-body">
    <table class="table">
      <%= render partial: 'ward' %>
      <% [:name, :birth_number, :address, :phone, :email, :postal_address].each do |column|%>
        <tr><th><%= Commisary.human_attribute_name(column) %></th><td><%=@commisary.send(column)%></td></tr>
      <% end %>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 col-sm-push-6">
    <%= link_to "Opravit údaje", edit_commisary_path(@commisary), class: "btn btn-lg btn-primary btn-block" if can? :edit, @commisary %>
  </div>
  <div class="col-sm-6 col-sm-pull-6">
    <%= link_to("Zrušit registraci", @commisary, method: :delete, data: {
          confirm: 'Opravdu chcete zrušit registraci do okrskové volební komise?',
          :'confirm-button-text' => 'Ano, chci zrušit',
          :'cancel-button-text' => 'Omyl, nechci nic rušit',
          :'confirm-button-color' => '#d9534f',
          text: 'Registrace bude okamžitě zrušena'
        }, class: "btn btn-lg btn-danger btn-block"
      ) if can? :destroy, @commisary
    %>
  </div>
</div>