config/routes.rb
Rails.application.routes.draw do

  get '/wards' => 'api#wards'
  get '/municipalities' => 'api#municipalities'
  get '/districts' => 'api#districts'

  # get 'welcome/index'
  #
  # get "exports/index"
  # get 'exports/regions'
  # get 'exports/municipalities'
  # get 'exports/wards'
  get '/exports/:region_id/index', to: 'exports#index', as: :export_region
  # get '/exports/:region_id/senat', to: 'exports#senat'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :commisaries, :controllers => {:registrations => "commisaries/registrations"}
  resources :commisaries, only: [:index, :show, :new, :destroy, :edit, :update]
  resources :events, only: [:index]
  resources :regions, only: [:index, :show]
  resources :users, only: [:index]

  # mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get '/users/:id' => "commisaries#index", as: "user"
  root 'welcome#index'

  get '/stats', to: 'stats#index'

  # get '/auth/:provider/callback', to: 'sessions#create'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/views/welcome/index.html.erb
<%
  page_title "Registrace do volebních komisí"
  breadcrumb :root
%>

<% if 1==0 %>
  <strong>Registrace do okrskových volebních komisí jsou již uzavřeny.</strong>
<% else %>
  <p class="perex">pro <%=configatron.votes_full_name%></p>
  <p>Pokud jste se rozhodli pracovat v dny voleb ve volební komisi, zaregistrujte se prosím. Podmínkou je české občanství a plnoletost.</p>
  <% if configatron.public_registration_allowed %>
  <p><%= link_to "Registrace do komisí pro voliče Svobodných >>", new_commisary_path, class: "btn btn-default btn-lg" %></p>
  <% else %>
  <p>Registrace do okrskových volebních komisí mohou provádět pouze členové a příznivci Svobodých. Příznivci mohou zaregistrovat pouze sebe, členové i další osoby.</p>
  <p>Zaregistrovaná osoba obdrží emailem vlastní přihlašovací údaje a může zde měnit své registrační údaje nebo svou registraci zrušit.</p>
  <% end %>
  <p>V případě nejasností se na nás můžete obrátit emailem na adrese <%=mail_to configatron.our_email %> nebo telefonicky na čísle 773 697 986.</p>
  <p>Registrace jsou otevřeny do <%=l configatron.registration_ends_at%></p>
  <% unless person_signed_in? %>
    <div class="panel panel-default">
      <div class="panel-heading">Vstup pro členy komisí - úprava svých údajů</div>
      <div class="panel-body">
        <p>Zaregistrovaná osoba obdrží emailem vlastní přihlašovací údaje a může zde měnit své registrační údaje nebo svou registraci zrušit.</p>
        <%= form_for(Commisary.new, url: commisary_session_path, html: {class: "form-inline"}) do |f| %>
          <div class="form-group">
            <%= f.label :email, class: "sr-only" %>
            <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "Email" %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: "sr-only"  %>
            <label class="sr-only" for="exampleInputPassword3">Heslo</label>
            <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Heslo" %>
          </div>
          <%= f.submit "Přihlásit", class: "btn btn-default" %>
        <% end %>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">Vstup pro členy uskupení Trikolóra Svobodní Soukromníci - registrace osob</div>
      <div class="panel-body">
        <div class="row">
        <%= link_to image_tag('https://www.svobodni.cz/wp-content/themes/Svobodni/images/logo3.png'), user_registr_omniauth_authorize_path, method: :post %></div>
        </div>
      </div>
    </div>
  <% else %>
    <% if user_signed_in? %>
      <%= link_to "Registrace >", commisaries_path, class: "btn btn-lg btn-primary pull-right" %>
      <%= link_to "Dopisy pro zmocněnce", regions_path, class: "btn btn-lg btn-default btn-primary" if can? :letter, Region %>
    <% elsif commisary_signed_in? %>
      <%= link_to "Registrace >", current_commisary, class: "btn btn-lg btn-primary pull-right" %>
    <% end %>
  <% end %>
<% end %>