config/routes.rb
Rails.application.routes.draw do

  get '/wards' => 'api#wards'
  get '/municipalities' => 'api#municipalities'
  get '/districts' => 'api#districts'

  # get 'welcome/index'
  #
  # get "exports/index"
  # get 'exports/regions'
  # get 'exports/municipalities'
  # get 'exports/wards'
  get '/exports/:region_id/index', to: 'exports#index', as: :export_region
  # get '/exports/:region_id/senat', to: 'exports#senat'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :commisaries, :controllers => {:registrations => "commisaries/registrations"}
  resources :commisaries, only: [:index, :show, :new, :destroy, :edit, :update]
  resources :events, only: [:index]
  resources :regions, only: [:index, :show]
  resources :users, only: [:index]

  # mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get '/users/:id' => "commisaries#index", as: "user"
  root 'welcome#index'

  get '/stats', to: 'stats#index'

  # get '/auth/:provider/callback', to: 'sessions#create'
end

app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js" lang="">
  <head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%=@page_title%></title>

    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <!-- Place favicon.ico in the root directory -->

    <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>


		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>

  </head>
  <body>
    <!--[if lt IE 10]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <div class="container">
      <div class="header">
      <header class="navbar navbar-default navbar-fixed-top bs-docs-nav" role="banner">
        <div class="container">
          <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" rel="home" href="/" title="Svobodní">
            <%= image_tag '02_SVOBODNI_logo_tagline.png'%>
            </a>
          </div>
          <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
            <% if person_signed_in? %>
              <ul class="nav navbar-nav navbar-right">
                <li class="dropdown active">
        	        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=current_person.name%> <b class="caret"></b></a>
        	        <ul class="dropdown-menu">
                    <% if user_signed_in? %>
                      <li><%= link_to "Registrace", commisaries_path %></li>
                      <% if can? :read, Event %><li><%= link_to "Události", events_path %></li><% end %>
                      <% if can? :read, User %><li><%= link_to "Uživatelé", users_path %></li><% end %>
                      <% if can? :read, User %><li><%= link_to "Statistiky", stats_path %></li><% end %>
                      <% if can? :letter, Region %><li><%= link_to "Dopisy", regions_path %></li><% end %>
                    <% elsif commisary_signed_in? %>
                      <li><%= link_to "Registrace", current_commisary %></li>
                    <% end %>
                    <li role="presentation" class="divider"></li>
        	          <li><%= link_to('Odhlásit se', destroy_session_path(current_person), method: :delete) %></li>
        	        </ul>
        	      </li>
            </ul>
            <% else %>
              <ul class="nav navbar-nav navbar-right">
                <li class="dropdown active">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Přihlášení <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Vstup pro členy komisí", new_commisary_session_path %></li>
                    <li><%= link_to "Vstup pro Svobodné", user_registr_omniauth_authorize_path, method: :post %></li>
                  </ul>
                </li>
              </ul>
            <% end %>
          </nav>
        </div>
      </header>
    </div>
      <div class="content">
        <%= bootstrap_flash %>
        <ul class="nav nav-pills pull-right">
          <%= breadcrumbs separator: " / " %>
        </ul>
        <div class="row">
          <div class="col-sm-12">
            <h1><%=@page_title%></h1>
						<%= yield %>
          </div>
        </div>

        <!-- <div class="jumbotron">
          <h1>'Allo, 'Allo!</h1>
          <p class="lead">Always a pleasure scaffolding your apps.</p>
          <p><a class="btn btn-lg btn-success" href="#">Splendid!</a></p>
        </div>
   -->
      </div>

      <div class="footer">
        <div class="row">
          <div class="col-sm-4"><%=link_to "www.svobodni.cz", "https://web.svobodni.cz"%></div>
          <div class="col-sm-4"><%=mail_to "kancelar@svobodni.cz", "kancelar@svobodni.cz"%></div>
          <div class="col-sm-4">tel. 773 697 986</div>
        </div>
      </div>
    </div>

    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script>
      (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
      function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
      e=o.createElement(i);r=o.getElementsByTagName(i)[0];
      e.src='https://www.google-analytics.com/analytics.js';
      r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
      ga('create','UA-XXXXX-X');ga('send','pageview');
    </script>

  </body>
</html>